package com.vegAppTest.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;
import lombok.Data;

@Data

@Entity // mark the class as JPA entity
@Table(name = "sync")

public class Sync {

    @Id // mark the field id as the primary key of the entity
    @Column(name = "id") // id is mapped to the user_id column in the users table
    @GeneratedValue(strategy = GenerationType.IDENTITY) // specify that the primary key values are
                                                        // automatically generated by the database. Values
                                                        // produced by an identity column in the database
                                                        // are auto-incremented
    private Long id;

    @Column(name = "gardener_id", unique = true)
    @JsonIgnore
    private Long gardener_id;

    @Column(name = "api_number")
    private Long api_number;

    @Column(name = "api_response", columnDefinition = "TEXT")

    private String api_response;

    public Sync() {

    }

    public Sync(Long gardener_id, Long api_number, String api_response) {

        this.gardener_id = gardener_id;
        this.api_number = api_number;
        this.api_response = api_response;
    }

}
