package com.vegAppTest.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

@Data

@Entity // mark the class as JPA entity
@Table(name = "vegetable", uniqueConstraints = { @UniqueConstraint(columnNames = { "name", "category_primary_id" }) })
public class Veggie {

    @Id // mark the field id as the primary key of the entity
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) // specify that the primary key values are
                                                        // automatically generated by the database. Values
                                                        // produced by an identity column in the database
                                                        // are auto-incremented
    private Long id;

    @Column(name = "name", length = 255)
    private String name;

    @Column(name = "seed_availability")
    private int seed_availability; // 0 or 1

    @Column(name = "seed_expiration")
    private int seed_expiration;

    @Column(name = "harvest_start")
    private int harvest_start;

    @Column(name = "harvest_end")
    private int harvest_end;

    @Column(name = "plant_start")
    private String plant_start;

    @Column(name = "plant_end")
    private String plant_end;

    @Column(name = "note", length = 1024)
    private String note;

    /* Relation Category - Veggie */
    @ManyToOne(cascade = {CascadeType.DETACH, CascadeType.MERGE})
    @JoinColumn(name = "category_secondary_id") 
    @JsonIgnore
    private CategorySecondary category_secondary;

    @Transient
    private Long category_secondary_id;

    /* Relation Category - Veggie */
    @ManyToOne
    @JoinColumn(name = "category_primary_id")
    @JsonIgnore
    private CategoryPrimary category_primary;

    @Transient
    private Long category_primary_id;

    @Transient
    private Long garden_id;

    /* Relation Plot - Veggie */
    @ManyToMany(mappedBy = "veggies")
    @JsonIgnore
    private List<Plot> plots;

    public Veggie() {

    }

    public Veggie(String name, int seed_availability, int seed_expiration, int harvest_start, int harvest_end,
            String plant_start, String plant_end, String note) {
        this.name = name;
        this.seed_availability = seed_availability;
        this.seed_expiration = seed_expiration;
        this.harvest_start = harvest_start;
        this.harvest_end = harvest_end;
        this.plant_start = plant_start;
        this.plant_end = plant_end;
        this.note = note;
    }

}